accessing
exception: anException
	"The original exception."

	exception := anException.